{% set name = "bioformats2raw" %}
{% set version = "0.11.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0

source:
  url: https://github.com/glencoesoftware/{{ name }}/releases/download/v{{ version
    }}/{{ name }}-{{ version }}.zip
  sha256: ea5352eb684ed989622559e2cd594077ce5f58b6fe375ede08518856622a3864

requirements:
  run:
  - openjdk
  - blosc

test:
  commands:
  - bioformats2raw a.fake output.zarr

extra:
  recipe-maintainers:
  - ome

about:
  home: https://www.glencoesoftware.com/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Bio-Formats image file format to raw format converter
  dev_url: https://github.com/glencoesoftware/bioformats2raw/
