{% set name = "bioformats2raw" %}
{% set version = "0.10.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0

source:
  url: https://github.com/glencoesoftware/{{ name }}/releases/download/v{{ version
    }}/{{ name }}-{{ version }}.zip
  sha256: db1e47b103056220eeab7be705e3d41e3ed74e80f5fd3b86975fa01c77680502

requirements:
  run:
  - openjdk
  - blosc

test:
  commands:
  - bioformats2raw a.fake output.zarr

extra:
  recipe-maintainers:
  - ome

about:
  home: https://www.glencoesoftware.com/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Bio-Formats image file format to raw format converter
  dev_url: https://github.com/glencoesoftware/bioformats2raw/
