{% set name = "bioformats2raw" %}
{% set version = "0.9.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0

source:
  url: https://github.com/glencoesoftware/{{ name }}/releases/download/v{{ version
    }}/{{ name }}-{{ version }}.zip
  sha256: fd0c2f6ad40047c35c43d1f9b547053f1c53335428350effca9feeda7aa8cfa0

requirements:
  run:
  - openjdk
  - blosc

test:
  commands:
  - bioformats2raw a.fake output
  - bioformats2raw --file_type=zarr -r 2 a.fake output.zarr

extra:
  recipe-maintainers:
  - ome

about:
  home: https://www.glencoesoftware.com/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Bio-Formats image file format to raw format converter
  dev_url: https://github.com/glencoesoftware/bioformats2raw/
