{% set name = "bioformats2raw" %}
{% set version = "0.7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 1

source:
  url: https://github.com/glencoesoftware/{{ name }}/releases/download/v{{ version
    }}/{{ name }}-{{ version }}.zip
  sha256: e94e3fd268bd144069d672899ee0b53182d2b3d71519d2fade8bfaedd6c7bf24

requirements:
  run:
  - openjdk

test:
  commands:
  - bioformats2raw a.fake output
  - bioformats2raw --file_type=zarr -r 2 a.fake output.zarr

extra:
  recipe-maintainers:
  - ome

about:
  home: https://www.glencoesoftware.com/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Bio-Formats image file format to raw format converter
  dev_url: https://github.com/glencoesoftware/bioformats2raw/
