{% set name = "bioformats2raw-libs" %}
{% set version = "0.6.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0
  noarch: generic

source:
  url: https://github.com/glencoesoftware/bioformats2raw/releases/download/v{{ version
    }}/bioformats2raw-{{ version }}.zip
  sha256: ca821ffb2a357a4ae15afd1c17848c4acd2ca905013183ad7ceb7b4e4b50643d

# Leave the OS specific dependencies to the wrapper
requirements:
  run:
  - blosc

extra:
  recipe-maintainers:
  - ome

about:
  home: https://www.glencoesoftware.com/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Bio-Formats image file format to raw format converter jars
  dev_url: https://github.com/glencoesoftware/bioformats2raw/
