{% set name = "bioformats2raw-libs" %}
{% set version = "0.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0
  noarch: generic

source:
  url: https://github.com/glencoesoftware/bioformats2raw/releases/download/v{{ version }}/bioformats2raw-{{ version }}.zip
  sha256: dbc74eee15b4ce46170aac67de9a1f2849b89b8d84ab55792140d30cd206f8e4

# Leave the OS specific dependencies to the wrapper
requirements:
  run:
    - blosc

extra:
  recipe-maintainers:
    - ome

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Bio-Formats image file format to raw format converter jars
  dev_url: https://github.com/glencoesoftware/bioformats2raw/
