name: Conda

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-12
          - macos-14
          - ubuntu-latest
          - windows-latest
      fail-fast: false

    steps:
      - name: setup-conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""
          miniconda-version: "latest"

      - name: Set conda-bld output folder to make it easier to find artifacts
        id: condablddir
        # On Windows /conda-bld and \\conda-bld work here but fail later
        # c:\\conda-bld seems to work.... for now
        run: |
          if [ ${{ matrix.os }} = windows-latest ]; then
            echo "condabld=c:\\conda-bld" >> $GITHUB_OUTPUT
          else
            echo "condabld=$HOME/conda-bld" >> $GITHUB_OUTPUT
            if [ ${{ matrix.os }} = macos-14 ]; then
              # Surprising that this is required. Locally, the directory includes "arm" automatically
              conda config --env --set subdir "osx-arm64"
            fi
          fi
        shell: bash

      - run: |
          echo "${{ steps.condablddir.outputs.condabld }}"
          mkdir ${{ steps.condablddir.outputs.condabld }}
          conda config --set conda_build.output_folder ${{ steps.condablddir.outputs.condabld }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install conda build
        run: conda install -y -q conda-build conda-verify

      - name: Build packages
        run: conda build .

      - run: ls -R "${{ steps.condablddir.outputs.condabld }}"

      - uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.os }}"
          path: "${{ steps.condablddir.outputs.condabld }}/*/bioformats2raw-*.tar.bz2"
          if-no-files-found: error

  upload:
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:

      - name: setup-conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""
          miniconda-version: "latest"

      - run: conda install -y -q anaconda-client

      - name: Download artifacts from build
        uses: actions/download-artifact@v4

      - name: List artifacts
        run: ls -R

      - name: Upload to Anaconda Cloud
        shell: bash -el {0}
        run: |
          anaconda whoami
          for f in */*/bioformats2raw*.tar.bz2; do
            if [[ "$f" == *"rc"* ]]; then
              anaconda upload --user ${ANACONDA_USER} $f --label pre
            else
              anaconda upload --user ${ANACONDA_USER} $f
            fi
          done
        env:
          ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
